ShopShoe/Areas/Admin/Controllers/ADKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopShoe.Models;

namespace ShopShoe.Areas.Admin.Controllers
{
    public class ADKhachHangController : Controller
    {
        // GET: Admin/ADKhachHang
        MyDb db = new MyDb();
        public ActionResult Index()
        {
            return View(db.KhachHangs.OrderByDescending(x => x.ID).ToList());
        }
        public ActionResult ChiTiet(int ID)
        {
            var chitiet = db.KhachHangs.SingleOrDefault(x => x.ID == ID);
            return View(chitiet);
        }
        [HttpGet]
        public ActionResult Them()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Them(User model)
        {
            db.Users.Add(model);
            db.SaveChanges();
            return View();
        }
    }
}

ShopShoe/Areas/Admin/Views/ADKhachHang/ChiTiet.cshtml
@model ShopShoe.Models.KhachHang

@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Khách Hàng</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
         
            <!-- /.panel-heading -->
            <div class="panel-body">
             <div class="col-md-12">
                 <div class="col-md-6">
                     <div class="panel panel-default">
                         <div class="panel-heading">Thông Tin Khách Hàng</div>
                         <div class="panel-body">
                             <div class="form-group">
                                 <label>Tên KH : </label>
                                 @Model.Ten
                             </div>
                             <div class="form-group">
                                 <label>Số điện thoại :</label>
                                 @Model.SDT
                             </div>
                             <div class="form-group">
                                 
                                 <label>Địa Chỉ : </label>
                                 @Model.DiaChi
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="col-md-6">
                     <div class="panel panel-default">
                         <div class="panel-heading">Thông Tin Đăng Nhập</div>
                         <div class="panel-body">
                             <div class="form-group">
                                 <label>Email : </label>
                                 @Model.Email
                             </div>
                             <div class="form-group">
                                 <label>Mật Khẩu</label>
                                 <input class="form-control col-md-6"  value="@Model.MatKhau" type="password" id="PassWord"/>
                                 <button class="btn btn-primary btn-sm" id="Show"><i class="fa fa-eye"></i></button>
                             </div>
                             
                         </div>
                     </div>
                 </div>
             </div>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>

</div>
@section scripts {
<script>
        $('#Show').on('click', function () {
            if ($('#PassWord').prop('type') == 'text') {
                $('#PassWord').prop('type', 'password');
                return;
            }
            if ($('#PassWord').prop('type') == 'password') {
                $('#PassWord').prop('type', 'text');
                return;
            }
        });
</script>
}

ShopShoe/Areas/Admin/Views/ADKhachHang/Index.cshtml
@model List<ShopShoe.Models.KhachHang>

@{
    ViewBag.Title = "KhachHang";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Khách hàng</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">

            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tên KH</th>
                            <th>SDT</th>
                            <th>Email</th>
                            <th>Địa Chỉ</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="odd gradeX">
                                <td>@item.ID</td>
                                <td>@item.Ten</td>
                                <td>@item.SDT</td>
                                <td>@item.Email</td>
                                <td>@item.DiaChi</td>
                                <td class="center">
                                    <a href="@Url.Action("ChiTiet","ADKhachHang",new {ID=item.ID})">Chi Tiết</a>
                                </td>

                            </tr>
                        }



                    </tbody>
                </table>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>

</div>